<a href="https://colab.research.google.com/github/2303a51729Ajaykumar/machine-learning/blob/main/Handling_imbalanced_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Imbalanced Dataset:**: A datasset with an unequal class distribution

In [1]:
import pandas as pd
import numpy as np

In [3]:
#loading the dataset into the pandas dataframe
credit_data=pd.read_csv('/content/credit_data.csv')

In [4]:
credit_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [5]:
credit_data.shape

(1986, 31)

In [6]:
credit_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
#distribution of the two classses
credit_data['Class'].value_counts()

Class
0.0    5970
1.0       3
Name: count, dtype: int64

this is highly imbalanced dataset

*   0 -> Legit Transaction
*   1 -> Fraudulent Transaction

In [7]:
#separeting the legit and Fraudulent
legit=credit_data[credit_data.Class==0]
fraud=credit_data[credit_data.Class==1]

In [8]:
print(legit.shape)
print(fraud.shape)

(1983, 31)
(2, 31)

under-sampling

Bulid the sample dataset containing similar distribution of Legit & Fradulent Transactionds

In [9]:
legit_sample=legit.sample(n=492)

In [10]:
print(legit_sample.shape)

(492, 31)

Concatenate the two DataFrames

In [11]:
new_dataset=pd.concat([legit_sample,fraud],axis=0)

In [12]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
980,742,1.304437,-0.709851,-0.112405,-2.207912,-0.355304,0.170636,-0.518525,0.050055,2.470382,...,0.065871,0.610271,-0.375163,-1.229720,0.948828,-0.485356,0.111789,0.012819,25.95,0.0
1714,1324,1.066220,-0.975274,0.558696,-0.275940,-1.283669,-0.600669,-0.432909,-0.109574,-0.532590,...,0.121159,0.194438,-0.052733,0.658793,0.374540,-0.262356,0.008349,0.038048,137.70,0.0
298,213,-0.263380,0.959103,0.285740,0.604068,3.228820,3.799503,0.715285,0.429148,-1.155492,...,-0.015245,0.059111,-0.291825,0.992903,-0.128938,-0.111063,-0.340206,-0.310297,4.38,0.0
835,636,0.962157,0.660079,-0.179635,0.733512,0.630849,0.223539,0.277339,0.008185,-0.381772,...,0.037153,0.229552,0.067054,-1.023487,-0.632746,-0.501300,0.002116,-0.139291,2.50,0.0
822,629,-0.667664,1.343777,1.313460,0.520482,-0.225132,-0.816066,0.433279,0.318095,-0.761124,...,-0.105448,-0.468959,-0.011037,0.331322,-0.064252,-0.670135,-0.046443,0.008504,4.00,0.0

In [13]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
265,188,1.168433,0.319978,0.589693,1.044774,-0.376942,-0.677335,0.054472,-0.087670,-0.304110,...,0.020051,0.066970,-0.017274,0.532429,0.502070,-0.470804,0.021893,0.019337,8.09,0.0
723,547,1.066851,-0.464679,1.984353,1.521834,-1.287325,1.113014,-1.314876,0.528953,0.249078,...,-0.080174,0.115724,0.149055,0.419153,-0.364680,3.087444,-0.137987,-0.016174,1.48,0.0
1025,774,-0.668959,1.247359,0.871030,-0.392539,0.421537,-0.173299,0.719178,-0.005268,0.110427,...,-0.396220,-0.850718,-0.139406,-0.626525,-0.039863,0.092990,0.285349,-0.029153,8.94,0.0
541,406,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1.0
623,472,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1.0

In [15]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0      2
Name: count, dtype: int64